/**
 * Generated Images Display Component
 * 
 * Displays featured and section images generated by v1.3.1
 * Shows image previews with alt text
 */

'use client';

import React from 'react';
import Image from 'next/image';

export interface GeneratedImage {
  type: 'featured' | 'section' | 'product';
  image_url: string;
  alt_text: string;
}

interface FeaturedImage {
  image_url?: string;
  image_data?: string | null;
  alt_text?: string;
  image_id?: string;
  width?: number;
  height?: number;
}

interface GeneratedImagesDisplayProps {
  featured_image?: FeaturedImage | null;
  generated_images?: GeneratedImage[];
  className?: string;
  showCount?: boolean;
}

export function GeneratedImagesDisplay({
  featured_image,
  generated_images,
  className = '',
  showCount = true
}: GeneratedImagesDisplayProps) {
  const hasFeatured = featured_image?.image_url || featured_image?.image_data;
  const hasSectionImages = generated_images && generated_images.length > 0;
  const totalCount = (hasFeatured ? 1 : 0) + (generated_images?.length || 0);
  
  if (!hasFeatured && !hasSectionImages) {
    return null;
  }

  return (
    <div className={`bg-green-50 border border-green-200 rounded-lg p-4 dark:bg-green-900/20 dark:border-green-800 ${className}`}>
      <div className="flex items-center mb-3">
        <svg className="w-5 h-5 text-green-600 dark:text-green-400 mr-2 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
          <path fillRule="evenodd" d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-8 3 6 2-4 3 6z" clipRule="evenodd" />
        </svg>
        <h3 className="text-green-800 dark:text-green-200 font-semibold text-sm">
          Generated Images
          {showCount && totalCount > 0 && (
            <span className="ml-2 text-green-600 dark:text-green-400 font-normal">
              ({totalCount} total)
            </span>
          )}
        </h3>
      </div>
      
      <div className="space-y-4">
        {hasFeatured && (
          <div>
            <p className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Featured Image
            </p>
            <div className="relative w-full h-48 rounded-lg overflow-hidden border border-gray-200 dark:border-gray-700 bg-gray-100 dark:bg-gray-800">
              {featured_image?.image_url ? (
                <Image
                  src={featured_image.image_url}
                  alt={featured_image.alt_text || 'Featured image'}
                  fill
                  className="object-cover"
                  sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                />
              ) : featured_image?.image_data ? (
                <img
                  src={featured_image.image_data}
                  alt={featured_image.alt_text || 'Featured image'}
                  className="w-full h-full object-cover"
                />
              ) : null}
            </div>
            {featured_image?.alt_text && (
              <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                {featured_image.alt_text}
              </p>
            )}
          </div>
        )}
        
        {hasSectionImages && (
          <div>
            <p className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Section Images ({generated_images!.length})
            </p>
            <div className="grid grid-cols-2 gap-2">
              {generated_images!.map((img, index) => (
                <div 
                  key={index} 
                  className="relative w-full h-32 rounded-lg overflow-hidden border border-gray-200 dark:border-gray-700 bg-gray-100 dark:bg-gray-800"
                >
                  <Image
                    src={img.image_url}
                    alt={img.alt_text}
                    fill
                    className="object-cover"
                    sizes="(max-width: 768px) 50vw, 25vw"
                  />
                </div>
              ))}
            </div>
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-2">
              Images automatically inserted into content at appropriate sections
            </p>
          </div>
        )}
      </div>
      
      {totalCount > 0 && (
        <p className="text-xs text-green-600 dark:text-green-400 mt-3 pt-2 border-t border-green-200 dark:border-green-700">
          ✅ v1.3.1: Images automatically generated and inserted into markdown
        </p>
      )}
    </div>
  );
}

