/**
 * Internal Links Display Component
 * 
 * Displays the 3-5 internal links automatically generated by v1.3.1
 * Shows anchor text and URLs for user review
 */

'use client';

import React from 'react';

export interface InternalLink {
  anchor_text: string;
  url: string;
}

interface InternalLinksDisplayProps {
  internal_links?: InternalLink[] | Array<Record<string, string>>;
  className?: string;
  showCount?: boolean;
}

export function InternalLinksDisplay({
  internal_links,
  className = '',
  showCount = true
}: InternalLinksDisplayProps) {
  if (!internal_links || internal_links.length === 0) {
    return null;
  }

  // Normalize links to handle different formats
  const normalizedLinks: InternalLink[] = internal_links.map(link => {
    if ('anchor_text' in link && 'url' in link) {
      return {
        anchor_text: String(link.anchor_text || link.anchor || ''),
        url: String(link.url || '')
      };
    }
    // Handle array of objects with different key names
    const keys = Object.keys(link);
    return {
      anchor_text: String(link[keys[0]] || ''),
      url: String(link[keys[1]] || link[keys[0]] || '')
    };
  }).filter(link => link.anchor_text && link.url);

  if (normalizedLinks.length === 0) {
    return null;
  }

  return (
    <div className={`bg-blue-50 border border-blue-200 rounded-lg p-4 dark:bg-blue-900/20 dark:border-blue-800 ${className}`}>
      <div className="flex items-center mb-3">
        <svg className="w-5 h-5 text-blue-600 dark:text-blue-400 mr-2 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
          <path d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z" />
          <path d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z" />
        </svg>
        <h3 className="text-blue-800 dark:text-blue-200 font-semibold text-sm">
          Internal Links
          {showCount && (
            <span className="ml-2 text-blue-600 dark:text-blue-400 font-normal">
              ({normalizedLinks.length})
            </span>
          )}
        </h3>
      </div>
      <ul className="space-y-2">
        {normalizedLinks.map((link, index) => (
          <li key={index} className="flex items-start text-sm">
            <span className="text-blue-700 dark:text-blue-300 font-medium mr-2 flex-shrink-0">
              &quot;{link.anchor_text}&quot;
            </span>
            <span className="text-gray-400 dark:text-gray-500 mx-1">→</span>
            <a
              href={link.url}
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-600 dark:text-blue-400 hover:underline ml-1 break-all"
              title={link.url}
            >
              {link.url.length > 50 ? `${link.url.substring(0, 50)}...` : link.url}
            </a>
          </li>
        ))}
      </ul>
      {normalizedLinks.length >= 3 && normalizedLinks.length <= 5 && (
        <p className="text-xs text-blue-600 dark:text-blue-400 mt-3 pt-2 border-t border-blue-200 dark:border-blue-700">
          ✅ v1.3.1: {normalizedLinks.length} internal links generated (expected: 3-5)
        </p>
      )}
    </div>
  );
}

